CREATE OR REPLACE TABLE PLACE(
	ID 				INT NOT NULL AUTO_INCREMENT,
	NAME 			VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	TYPE			INT NOT NULL,
	PARENT			INT,
	PRIMARY KEY(ID),
	FOREIGN KEY(TYPE) REFERENCES TYPE_OF_PLACE(ID),
	FOREIGN KEY(PARENT) REFERENCES PLACE(ID)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;