CREATE OR REPLACE TABLE REGISTER(
	PUBLICATION			INT NOT NULL,
	AREA				INT NOT NULL,
	FOREIGN KEY(PUBLICATION) REFERENCES PUBLICATION(ID),
	FOREIGN KEY(AREA) REFERENCES AREA(ID)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;