CREATE OR REPLACE TABLE ENROLL(
	DESCRIPTION		VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_spanish_ci,
	USERNAME		VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	AREA			INT NOT NULL,
	FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
	FOREIGN KEY(AREA) REFERENCES AREA(ID)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;