CREATE OR REPLACE TABLE PUBLICATION(
	ID				INT NOT NULL AUTO_INCREMENT,
	NAME			VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	URL				VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	START_DATE		DATE NOT NULL,
	END_DATE 		DATE,
	PLACE			VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_spanish_ci,
	CALIFICATION	INT,
	POSITION		VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_spanish_ci,
	TYPE			INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(TYPE) REFERENCES TYPE_OF_PUBLICATION(ID)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;