CREATE OR REPLACE TABLE ACADEMIC_INSTITUTION(
	ID 				INT NOT NULL AUTO_INCREMENT,
	NAME 			VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	EMAIL			VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	PHONE			VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	DESCRIPTION		VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	UBICATION		VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	TYPE			INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(TYPE) REFERENCES TYPE_OF_ACADEMIC_INSTITUTION(ID)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;