CREATE OR REPLACE TABLE USER(
	USERNAME		VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	PASSWORD		VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	FULLNAME		VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	EMAIL			VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	PHONE			VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
	TYPE			INT NOT NULL,
	PRIMARY KEY(USERNAME),
	FOREIGN KEY(TYPE) REFERENCES TYPE_OF_USER(ID)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;