INSERT INTO TYPE_OF_PUBLICATION(VALUE) VALUES ('CONVOCATORIA DOCENTE');
INSERT INTO TYPE_OF_PUBLICATION(VALUE) VALUES ('REVISTA CIENTIFICA');
INSERT INTO TYPE_OF_PUBLICATION(VALUE) VALUES ('EVENTO ACADEMICO');