INSERT INTO TYPE_OF_ACADEMIC_INSTITUTION(VALUE) VALUES ('UNIVERSIDAD PÚBLICA');
INSERT INTO TYPE_OF_ACADEMIC_INSTITUTION(VALUE) VALUES ('UNIVERSIDAD PRIVADA');
INSERT INTO TYPE_OF_ACADEMIC_INSTITUTION(VALUE) VALUES ('INSTITUCIÓN PÚBLICA');
INSERT INTO TYPE_OF_ACADEMIC_INSTITUTION(VALUE) VALUES ('INSTITUCIÓN PRIVADA');